# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.PositiveIntegerField(default=50)),
                ('requires_authorization', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='organizations.station')),
            ],
            options={
                'verbose_name': 'Área operacional',
                'verbose_name_plural': 'Áreas operacionais',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('tank', 'Tanque'), ('pump', 'Bomba'), ('vessel', 'Vaso de pressão'), ('compressor', 'Compressor'), ('flare', 'Flare'), ('api_box', 'Caixa API'), ('valve', 'Válvula'), ('pipeline', 'Duto/Tubulação'), ('other', 'Outro')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='operations.operationalarea')),
            ],
            options={
                'verbose_name': 'Ativo/Equipamento',
                'verbose_name_plural': 'Ativos/Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='OperationalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='routes', to='operations.operationalarea')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='organizations.station')),
            ],
            options={
                'verbose_name': 'Rota operacional',
                'verbose_name_plural': 'Rotas operacionais',
            },
        ),
    ]
