# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'unique_together': {('code', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_item', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('instruction', models.TextField()),
                ('category', models.CharField(choices=[('operational_routine', 'Rotina da operação'), ('critical_task', 'Tarefa crítica'), ('equipment_release', 'Liberação de equipamento'), ('operational_return', 'Retorno operacional'), ('shift_handover', 'Passagem de serviço'), ('safety_dialogue', 'Diálogo de segurança')], default='operational_routine', max_length=40)),
                ('criticality', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_geolocation', models.BooleanField(default=False)),
                ('requires_observation', models.BooleanField(default=False)),
                ('can_generate_service_request', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='operations.operationalarea')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='operations.asset')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='routines.proceduredocument')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='operations.operationalroute')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='organizations.station')),
            ],
            options={
                'verbose_name': 'Rotina',
                'verbose_name_plural': 'Rotinas',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_value_input', models.BooleanField(default=False)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routines.routine')),
            ],
            options={
                'verbose_name': 'Etapa da rotina',
                'verbose_name_plural': 'Etapas da rotina',
                'ordering': ['order'],
            },
        ),
    ]
