# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('claimed', 'Assumida'), ('in_progress', 'Em execução'), ('completed', 'Concluída'), ('late', 'Atrasada'), ('not_done', 'Não realizada'), ('blocked', 'Bloqueada'), ('sync_pending', 'Sincronização pendente')], default='pending', max_length=30)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('outside_geofence_justification', models.TextField(blank=True)),
                ('has_abnormality', models.BooleanField(default=False)),
                ('service_request_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_executions', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='routines.routine')),
            ],
            options={
                'verbose_name': 'Execução de rotina',
                'verbose_name_plural': 'Execuções de rotinas',
            },
        ),
        migrations.CreateModel(
            name='ExecutionStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_results', to='routines.routinestep')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='execution.routineexecution')),
            ],
            options={
                'verbose_name': 'Resultado da etapa',
                'verbose_name_plural': 'Resultados das etapas',
            },
        ),
        migrations.CreateModel(
            name='Abnormality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('risk_to_people', models.BooleanField(default=False)),
                ('environmental_risk', models.BooleanField(default=False)),
                ('equipment_integrity_risk', models.BooleanField(default=False)),
                ('communicated_to_supervisor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormalities', to='execution.routineexecution')),
            ],
            options={
                'verbose_name': 'Anormalidade',
                'verbose_name_plural': 'Anormalidades',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_system', models.CharField(default='Sistema de manutenção', max_length=80)),
                ('external_code', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abnormality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='execution.abnormality')),
            ],
            options={
                'verbose_name': 'Registro de SS',
                'verbose_name_plural': 'Registros de SS',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='scheduling.shift')),
            ],
            options={
                'verbose_name': 'Sessão de trabalho',
                'verbose_name_plural': 'Sessões de trabalho',
            },
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='work_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='execution.worksession'),
        ),
    ]
