# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Exclusão'), ('login', 'Login'), ('sync', 'Sincronização')], max_length=20)),
                ('model_name', models.CharField(max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
            },
        ),
    ]
