# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operation_manager', 'Gerente de operação'), ('coordinator', 'Coordenador/Líder'), ('supervisor', 'Supervisor de operação'), ('control_room_operator', 'Operador de sala de controle'), ('field_operator', 'Operador de estação'), ('operations_assistant', 'Assistente de operações')], max_length=40)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil operacional',
                'verbose_name_plural': 'Perfis operacionais',
            },
        ),
    ]
