# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('abnormalities_summary', models.TextField(blank=True)),
                ('service_requests_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_reports', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_report', to='execution.worksession')),
            ],
            options={
                'verbose_name': 'Relatório de passagem de serviço',
                'verbose_name_plural': 'Relatórios de passagem de serviço',
            },
        ),
        migrations.CreateModel(
            name='PunctualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('total_routines', models.PositiveIntegerField(default=0)),
                ('completed_on_time', models.PositiveIntegerField(default=0)),
                ('completed_late', models.PositiveIntegerField(default=0)),
                ('not_done', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuality_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score de pontualidade',
                'verbose_name_plural': 'Scores de pontualidade',
                'unique_together': {('operator', 'reference_date')},
            },
        ),
    ]
