# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organizations.station')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('once_per_shift', 'Uma vez por turno'), ('shift_start', 'Início do turno'), ('shift_end', 'Fim do turno'), ('every_x_hours', 'A cada X horas'), ('daily', 'Diária'), ('weekly', 'Semanal'), ('specific_weekdays', 'Dias específicos da semana'), ('fixed_time', 'Horário fixo'), ('on_demand', 'Sob demanda'), ('campaign', 'Campanha/Cronograma')], max_length=40)),
                ('interval_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fixed_time', models.TimeField(blank=True, null=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('window_before_minutes', models.PositiveIntegerField(default=0)),
                ('window_after_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='routines.routine')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rules', to='scheduling.shift')),
            ],
            options={
                'verbose_name': 'Regra de agendamento',
                'verbose_name_plural': 'Regras de agendamento',
            },
        ),
    ]
